Extract intent and entities using luis bot api - first stage
amartyaamp/NestorBot pull request #7
Opened 2018-01-31 18:23 UTC by sreeragkiyyath

2018-01-31 18:49 UTC, sreeragkiyyath commented
Please add the key while using luis_setter.py

2018-02-01 15:36 UTC, amartyaamp commented
Can you post the test code which creates LuisBotSetter object and calls getTokens and show the output ?
Preferably in a separate test.py .

2018-02-02 19:05 UTC, amartyaamp commented
Can you test with the string - _" send a mail to abc@gmail.com "_ ?  
On my side it did not return any intent.

2018-02-03 17:13 UTC, sreeragkiyyath commented
Try again, Please list out unsuccessful queries here

2018-02-04 07:02 UTC, amartyaamp requested changes
Some changes that are required before we can plugin.

2018-02-04 07:02 UTC, amartyaamp commented on src/luis_setter.py
> +      print(returnString)
Function don't return anything!

2018-02-04 07:02 UTC, amartyaamp commented on src/luis_setter.py
> +      returnString = "intent:" + intentFromQuery +",entity:("
Do not return a raw string. Form a dictionary of the result and return the json dump. Using json.dumps(dictionary)

2018-02-04 07:02 UTC, amartyaamp commented on src/luis_setter.py
> +      returnString = "intent:" + intentFromQuery +",entity:("
Try forming a dictionary such that -  

1. **_tokens['intent']_** gives me the top scoring intent.
2. **_tokens['entities']_** gives me a list of entities in the statement.

Create a **_json_tokens = json.dumps(tokens)_** and return this

2018-02-04 07:10 UTC, amartyaamp commented
@sreeragkiyyath  
Till now following are the unsuccessful queries - 
1.  _Do i have any mail from abc@xyz.com ?_ ---- > **_intent:Calendar.Find,entity:(0:abc@xyz.com(),)_**
   This is not related to Calendar.

2018-02-16 06:20 UTC, merged